Employee Class Reference
Holds employee information.
#include `hw07-business-corp-employee-management-system-BrightS0le/Employee.h`
Public Member Functions
Employee (int ID, int years, double hourlyRate, float hoursWorked)
virtual double calculatePay ()
virtual void print ()
void anniversary ()
Protected Attributes
int years
double hourlyRate
float hoursWorked
double pay
Private Attributes
int ID
Detailed Description
Holds employee information.
The employee class
Member Function Documentation
anniversary()
void Employee::anniversary ()
prints out the aniversary statement for an employees year amount
Precondition
variables exist and are intialized, properly called, etc.
Returns
void
Postcondition
modifies hourlyRate and year amount
Referenced by runEmployeeTests().
calculatePay()
double Employee::calculatePay () [virtual]
Calculates the amount of money an employee will be paid
Precondition
For it to run the employee must exist at the company, and have properly intialized horuly rate and hours worked
Returns
virtual returns pay for employee
Postcondition
Reimplemented in Supervisor, and Officer.
Referenced by Supervisor::calculatePay(), and runEmployeeTests().
print()
void Employee::print () [virtual]
Prints out the information for an employee in the designated format
Precondition
Employee and it's variables exist and are properly intialized
Returns
virtual does not return anything
Postcondition
Reimplemented in Supervisor, and Officer.
Referenced by Officer::print(), Supervisor::print(), and runEmployeeTests().
The documentation for this class was generated from the following files:
Employee.h
Employee.cpp